# Generated by Django 3.2.5 on 2021-08-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustNum', models.AutoField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=50)),
                ('CustAddr', models.CharField(max_length=50)),
                ('Lang', models.CharField(choices=[('EN', '英语'), ('ZH', '汉语'), ('ES', '西班牙语'), ('FR', '法语'), ('PT', '葡萄牙语'), ('DE', '德语')], default='ZH', max_length=3)),
                ('Div', models.CharField(choices=[('BI', '自行车'), ('AS', '配件'), ('00', '自行车&配件'), ('01', '其他')], default='BI', max_length=3)),
                ('CustCur', models.CharField(choices=[('CNY', '人民币'), ('HKD', '港元'), ('TWD', '台币'), ('EUR', '欧元'), ('USD', '美元'), ('GBP', '英镑'), ('JPY', '日元')], default='CNY', max_length=3)),
                ('SearchTerm', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('MatNum', models.AutoField(primary_key=True, serialize=False)),
                ('MatName', models.CharField(max_length=50)),
                ('Weight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('MatDesc', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrdNum', models.AutoField(primary_key=True, serialize=False)),
                ('OrdCur', models.CharField(choices=[('CNY', '人民币'), ('HKD', '港元'), ('TWD', '台币'), ('EUR', '欧元'), ('USD', '美元'), ('GBP', '英镑'), ('JPY', '日元')], default='CNY', max_length=3)),
                ('OdrCreDate', models.DateField(auto_now_add=True)),
                ('DelDdl', models.DateField()),
                ('IsPost', models.BooleanField(default=False)),
                ('TotDisc', models.DecimalField(decimal_places=5, max_digits=5)),
                ('PayCustNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PayCustNum', to='data.customer')),
                ('RcvCustNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RcvCustNum', to='data.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantNum', models.AutoField(primary_key=True, serialize=False)),
                ('PlantName', models.CharField(max_length=50)),
                ('PlantLoc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlantMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.IntegerField()),
                ('PM_MatNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.material')),
                ('PM_PlantNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='materials',
            field=models.ManyToManyField(through='data.PlantMat', to='data.Material'),
        ),
        migrations.CreateModel(
            name='OrdMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdMatDesc', models.CharField(max_length=50)),
                ('OrdMatQty', models.IntegerField()),
                ('OdrMatDisc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('OM_MatNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.material')),
                ('OM_OrdNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.ManyToManyField(through='data.OrdMat', to='data.Material'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DelNum', models.AutoField(primary_key=True, serialize=False)),
                ('DelCreDate', models.DateField(auto_now_add=True)),
                ('PostDdl', models.DateField()),
                ('PostDate', models.DateField(blank=True, null=True)),
                ('DelOrdNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='DelPlant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.plant'),
        ),
    ]
